zeppelin:
  image: dylanmei/zeppelin:0.7.2
  resources:
    limits:
      memory: "2024Mi"
      cpu: "1000m"

hadoop:
  useConfigMap: false
  configMapName: hadoop-hadoop
  configPath: /usr/hadoop-2.7.3/etc/hadoop

spark:
  driverMemory: 1g
  executorMemory: 1g
  numExecutors: 2